modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MelanX/aiotbotania/issues/"
[[mods]]
modId="aiotbotania"
version="${file.jarVersion}"
displayName="AIOT Botania"
updateJSONURL="https://raw.githubusercontent.com/MelanX/aiotbotania/master/update/Update.json"
displayURL="https://minecraft.curseforge.com/projects/aiot-botania"
logoFile="logo.png"
credits="Vazkii for Botania and derkalaender for supporting me."
authors="MelanX, derkalaender"
description='''
This mod adds AIOTs. Because an AIOT is so much better than just a tool.
'''

[[dependencies.aiotbotania]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="botania"
    mandatory=true
    versionRange="[r1.15-381,)"
    ordering="NONE"
    side="BOTH"