modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/MelanX/aiotbotania/issues/"
license="MIT License"

[[mods]]
modId="aiotbotania"
version="${file.jarVersion}"
displayName="AIOT Botania"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/aiotbotania.json"
displayURL="https://minecraft.curseforge.com/projects/aiot-botania"
credits="Vazkii for Botania and derkalaender for supporting me."
authors="MelanX, derkalaender"
description='''
This mod adds AIOTs. Because an AIOT is so much better than just a tool.
'''

[[dependencies.aiotbotania]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.76,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="botania"
    mandatory = true
    versionRange = "[1.18.1-428,)"
    ordering = "NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="mythicbotany"
    mandatory=false
    versionRange="[1.18.1, 1.19)"
    ordering="NONE"
    side="BOTH"