modLoader="javafml"
loaderVersion="[${fml},)"
issueTrackerURL="https://github.com/MelanX/aiotbotania/issues/"
license="MIT License"

[[mods]]
modId="aiotbotania"
version="${version}"
displayName="AIOT Botania"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/aiotbotania.json"
displayURL="https://minecraft.curseforge.com/projects/aiot-botania"
credits="Vazkii for Botania and derkalaender for supporting me."
authors="MelanX, derkalaender"
description='''
This mod adds AIOTs. Because an AIOT is so much better than just a tool.
'''

[[dependencies.aiotbotania]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="botania"
    mandatory=true
    versionRange="[1.18.2-430,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="mythicbotany"
    mandatory=false
    versionRange="[1.18.1, 1.19)"
    ordering="NONE"
    side="BOTH"
