modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/MelanX/aiotbotania/issues/"
license="MIT License"

[[mods]]
modId="aiotbotania"
version="${file.jarVersion}"
displayName="AIOT Botania"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/aiotbotania.json"
displayURL="https://minecraft.curseforge.com/projects/aiot-botania"
logoFile="logo.png"
credits="Vazkii for Botania and derkalaender for supporting me."
authors="MelanX, derkalaender"
description='''
This mod adds AIOTs. Because an AIOT is so much better than just a tool.
'''

[[dependencies.aiotbotania]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.75,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiotbotania]]
    modId="botania"
    mandatory=true
    versionRange="[r1.16-398,)"
    ordering="NONE"
    side="BOTH"