name: Feature request
description: Suggest an idea, or enhancement
labels: [ enhancement ]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your idea
      placeholder: A clear and reasoned description of your idea.
    validations:
      required: true